
INSERT INTO FOURNISSEUR (NOM) VALUES ("Française d’Imports");

INSERT INTO ARTICLE (REF, DESIGNATION, PRIX, ID_FOU) VALUES ("A01", "Perceuse P1", "74.00", "1");
INSERT INTO ARTICLE (REF, DESIGNATION, PRIX, ID_FOU) VALUES ("A02", "Meuleuse 125mm", "37.85", "1");
INSERT INTO ARTICLE (REF, DESIGNATION, PRIX, ID_FOU) VALUES ("A03", "Perceuse à colonne", "185.25", "1");

UPDATE ARTICLE SET PRIX="74.99" WHERE REF="A01";

INSERT INTO BON (NUMERO, `DATE_CMDE`, `DELAI`,`ID_FOU`) VALUES (1234, CURRENT_TIMESTAMP, 3, 1);

INSERT INTO COMPO (`QTE`, `ID_ART`, `ID_BON`) VALUES (3, 1, (SELECT id FROM BON WHERE NUMERO=1234));
INSERT INTO COMPO (`QTE`, `ID_ART`, `ID_BON`) VALUES (4, 2, (SELECT id FROM BON WHERE NUMERO=1234));
INSERT INTO COMPO (`QTE`, `ID_ART`, `ID_BON`) VALUES (1, 3, (SELECT id FROM BON WHERE NUMERO=1234));